PresentationLayer/ViewModels/CategoryViewModel.cs
using BusinessLogicLayer.ServiceContracts.DTO;
using DataAccessLayer.Entities;

namespace PresentationLayer.ViewModels
{
    public class CategoryViewModel
    {
        public Category? Category { get; set; }
        public List<Category>? Categories { get; set; }
        public CategoryAddRequest? categoryAddRequest { get; set; }
        public List<CategoryResponse?> categoryResponse { get; set; }
        public CategoryUpdateRequest? categoryUpdateRequest { get; set; }
    }
}

PresentationLayer/Controllers/CategoryController.cs
using BusinessLogicLayer.ServiceContracts;
using BusinessLogicLayer.ServiceContracts.DTO;
using DataAccessLayer.Entities;
using DataAccessLayer.Interfaces.Repositories;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.ViewModels;

namespace PresentationLayer.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoriesService _categoriesService;
        public CategoryController(ICategoriesService categoriesService)
        {
            _categoriesService = categoriesService;
        }

        public async Task<IActionResult> Index()
        {
           

            List<CategoryResponse> categories = await _categoriesService.GetAllCategories();
            CategoryViewModel viewModel = new CategoryViewModel();

            viewModel.categoryResponse = categories;
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Create(CategoryAddRequest? categoryAddRequest)
        {
            if (categoryAddRequest != null)
            {
                CategoryResponse? response = await _categoriesService.AddCategory(categoryAddRequest);
            }

            return RedirectToAction ("Index");
        }



        [HttpGet]
        public async Task<IActionResult> Edit(Guid ID)
        {
            List<CategoryResponse> categories = await _categoriesService.GetAllCategories();

            CategoryResponse? categoryResponse = await _categoriesService.GetCategoryByID(ID);
            if(categoryResponse == null)return RedirectToAction("Index");

            CategoryUpdateRequest categoryUpdateRequest = categoryResponse.ToCategoryUpdateRequest();


            CategoryViewModel viewModel = new CategoryViewModel();

            viewModel.categoryResponse = categories;
            viewModel.categoryUpdateRequest = categoryUpdateRequest;

            return View(viewModel);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(CategoryUpdateRequest categoryUpdateRequest)
        {

            CategoryResponse? categoryResponse = await _categoriesService.GetCategoryByID(categoryUpdateRequest.ID);

            if (categoryResponse == null) 
            {
                return RedirectToAction("Index");
            }

            CategoryResponse? updateCategory  = await _categoriesService.UpdateCategory(categoryUpdateRequest);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid ID)
        {
            await _categoriesService.DeleteCategoryByID(ID);
            return RedirectToAction("Index");
        }



    }
}

PresentationLayer/Controllers/ProductController.cs
using BusinessLogicLayer.ServiceContracts;
using BusinessLogicLayer.ServiceContracts.DTO;
using DataAccessLayer.Entities;
using DataAccessLayer.Interfaces.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;
using System;
using System.Reflection.Metadata.Ecma335;

namespace PresentationLayer.Controllers
{
    
    public class ProductController : Controller
    {
        private readonly ICategoriesService _categoriesService;
        private readonly IProductsService _productsService;
        public ProductController(ICategoriesService categoriesService,IProductsService productsService)
        {
            _categoriesService = categoriesService;
            _productsService = productsService;
        }


        public async Task<IActionResult> Index(DateTime date)
        {
            List<ProductResponse> matchingProducts;

            if (date == DateTime.MinValue)
            {
                matchingProducts = await _productsService.GetAllProducts();
                if (matchingProducts == null) RedirectToAction("Create");
            }
            else
            {
                matchingProducts = await _productsService.GetFilterProducts(date);
                return PartialView(matchingProducts);
            }
       
            return View(matchingProducts);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task< IActionResult> Create()
        {

            List<CategoryResponse> categories = await _categoriesService.GetAllCategories();
            ViewBag.Categories = categories.Select(temp =>
              new SelectListItem() { Text = temp.CategoryName, Value = temp.ID.ToString() }
            );

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(ProductAddRequest product)
        {
            //Sending data to the products service to add new product to the Products table
            ProductResponse? productResponse = await _productsService.AddProduct(product);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid ID)
        {
            
            List<CategoryResponse> categories = await _categoriesService.GetAllCategories();
            ViewBag.Categories = categories.Select(temp =>
              new SelectListItem() { Text = temp.CategoryName, Value = temp.ID.ToString() }
            );

            ProductResponse? productResponse = await _productsService.GetProductByID(ID);
            ProductUpdateRequest? productUpdateRequest =  productResponse?.ToProductUpdateRequest();

            return View(productUpdateRequest);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(ProductUpdateRequest productUpdateRequest)
        {
            ProductResponse? productResponse = await _productsService.GetProductByID(productUpdateRequest.ProductID);

            if (productResponse == null)
            {
                return RedirectToAction("Index");
            }
            //Sending modified products details to the products service 
            ProductResponse? updateProduct = await _productsService.UpdateProduct(productUpdateRequest);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(Guid ID)
        {
            await _productsService.DeleteProductByID(ID);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> ProductsPDF()
        {
            List<ProductResponse> products = await _productsService.GetAllProducts();
            return new ViewAsPdf("ProductsPDF", products, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }




    }
}

PresentationLayer/Controllers/SaleController.cs
using BusinessLogicLayer.ServiceContracts;
using BusinessLogicLayer.ServiceContracts.DTO;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;
using System.Reflection.Metadata.Ecma335;

namespace PresentationLayer.Controllers
{
    public class SaleController : Controller
    {
        private readonly ICategoriesService _categoriesService;
        private readonly IProductsService _productsService;
        private readonly ISalesService _salesService;
        private readonly IStocksService _stocksService;
        public SaleController(ICategoriesService categoriesService, IProductsService productsService,ISalesService salesService, IStocksService stocksService)
        {
            _categoriesService = categoriesService;
            _productsService = productsService;
            _salesService = salesService;
            _stocksService = stocksService;
        }


        //privides the all sales details
        public async Task<IActionResult> Index(DateTime date)
        {

            List<Sale> matchingSale;

            if (date == DateTime.MinValue)
            {
                matchingSale = await _salesService.GetAllSales();
            }
            else
            {
                matchingSale = await _salesService.GetFilterSales(date);
                return PartialView(matchingSale);
            }

           
            return View(matchingSale);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddSale()
        {
            List<CategoryResponse> categories = await _categoriesService.GetAllCategories();
            //sending categroy to the view with key value pair
            ViewBag.Categories = categories.Select(temp =>
              new SelectListItem() { Text = temp.CategoryName, Value = temp.ID.ToString() }
            );

            ViewBag.Products = new List<SelectListItem>();
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddSale(Sale sale)
        {
            //adding new product to the sales table
            await _salesService.AddSale(sale);
            return RedirectToAction("Index");
        }


        //Get all stock product and return Product Name and product ID as a selectListItem
        [HttpGet]
        public async Task<ActionResult> GetProducts(string categoryID)
        {
            List<ProductResponse> products = await _productsService.GetAllProducts();

            //   var filterProducts = products.Where(prod => prod.CategoryID.ToString() == categoryID).ToList();

            List<Stock> stocks = await _stocksService.GetAllStockProducts();

            List<SelectListItem> productsSel = stocks.Where(st => st.CategoryID.ToString()==categoryID).Select(c => new SelectListItem()
            {
                Text = c.Product?.ProductName,
                Value = c.Product?.ProductID.ToString()
            }).ToList();
            return Json(productsSel);
        }


        [HttpGet]
        public async Task<ActionResult> GetSelectedProducts(string categoryID,string productID)
        {
            Stock stock = await _stocksService.GetProductByCtIdProdId(categoryID, productID);

            return Json(stock);

        }



        [HttpGet]
        public async Task<IActionResult> SalesPDF()
        {

            List<Sale> sales = await _salesService.GetAllSales();

            return new ViewAsPdf(sales);
        }




    }
}

PresentationLayer/Controllers/StockController.cs
using BusinessLogicLayer.ServiceContracts;
using BusinessLogicLayer.ServiceContracts.DTO;
using BusinessLogicLayer.Services;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;

namespace PresentationLayer.Controllers
{
    public class StockController : Controller
    {
        private readonly IStocksService _stocksService;
        public StockController(IStocksService stocksService)
        {
            _stocksService = stocksService;
        }
        public async Task<IActionResult> Index()
        {
            List<Stock> stocks = await _stocksService.GetAllStockProducts();
            return View(stocks);
        }


        public async Task<IActionResult> StocksPDF()
        {
            List<Stock> stocks = await _stocksService.GetAllStockProducts();
            return new ViewAsPdf("StocksPDF", stocks, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }


    }
}

PresentationLayer/Views/Shared/_CategoryTable.cshtml
@using BusinessLogicLayer.ServiceContracts.DTO


<div class="panel panel-default">
    <div class="panel-heading">
        <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>All Categories</span>
        </strong>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th class="text-center" style="width: 50px;">#</th>
                    <th>Categories</th>
                    <th class="text-center" style="width: 100px;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int index = 0;

                    foreach (CategoryResponse? categoryResponse in Model.categoryResponse)
                    {
                        index++;
                        <tr>
                            <td class="text-center">@index</td>
                            <td>@categoryResponse?.CategoryName</td>
                            <td>
                                <a asp-controller="Category" asp-action="Edit" asp-route-ID="@categoryResponse?.ID"><i class="fa fa-edit"></i></a>
                                <a asp-controller="Category" asp-action="Delete" asp-route-ID="@categoryResponse?.ID"><i class="fa fa-trash text-danger"></i></a>

                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - PresentationLayer</title>
         
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/PresentationLayer.styles.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="~/stylesheet.css" rel="stylesheet" />

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>


    </head>
    <body>

        <div class="mx-auto" style="width:95%">
            <main role="main" class="pb-3">
                <div class="row">
                    <div class="col-2 bg-light">

                        <nav  class=" d-lg-block  bg-white">
                            <div class="position-sticky">
                                <div class="list-group list-group-flush mx-3 " style="padding-top:70px;padding-bottom:500px">

                                    <a asp-controller="Category" asp-action="Index" class="list-group-item list-group-item-action py-2 ripple border-top text-dark"><i class="fas fa-shop fa-fw me-3"></i><span>Categories</span></a>

                                    <a id="purchase" asp-controller="Product" asp-action="Index" class="list-group-item list-group-item-action py-2 ripple text-dark"><i class="fas fa-shopping-cart fa-fw me-3"></i><span>Purchase</span> </a>


                                    <a asp-controller="Sale" asp-action="Index" class="list-group-item list-group-item-action py-2 ripple text-dark"><i class="fas fa-building fa-fw me-3"></i><span>Sales</span></a>

                                    <a asp-controller="Stock" asp-action="Index" class="list-group-item list-group-item-action py-2 ripple text-dark"><i class="fas fa-chart-line fa-fw me-3"></i><span>Stocks</span></a>

                                    <a href="#" class="list-group-item list-group-item-action py-2 ripple  border-bottom text-dark"><i class="fas fa-users fa-fw me-3"></i><span>Users</span></a>

                                </div>
                            </div>
                        </nav>


                    </div>
                    <div class="col-10">
                        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
                            <div class="container-fluid">

                                
                                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                    <ul class="navbar-nav flex">
                                        <li class="nav-item">
                                            <a href="#"><h4 class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inventory</h4></a>
                                        </li>
                                    </ul>

                                    <ul class="navbar-nav flex">
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <li class="nav-item nav-link text-dark">
                                                <i class="fa-solid fa-user px-1"></i>@User.Identity?.Name
                                            </li>
                                                <li class="nav-item">
                                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                                            </li>
                                        }
                                        else
                                        {
                                            @if (ViewBag.CurrentUrl == "~/Account/Register")
                                            {
                                                <li class="nav-item">
                                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register" class="nav-active">Register</a>
                                                </li>
                                            }
                                            else
                                            {
                                                        <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                                                </li>
                                            }


                                            @if (ViewBag.CurrentUrl == "~/Account/Login")
                                            {
                                                          <li>
                                                           <a class="nav-link text-dark" asp-controller="Account" asp-action="Login" class="nav-active">Login</a>
                                                          </li>
                                            }
                                            else
                                            {
                                                          <li>
                                                                   <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                                                          </li>
                                            }

                                        }
                                   </ul>
                                </div>
                            </div>
                        </nav>

                    @RenderBody()
                    </div>
                </div>

            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>